# Importing Libraries

In [1]:
import numpy as np
import pandas as pd

# Importing Dataset

In [3]:
dataset = pd.read_csv('/home/piyush/Desktop/Day1.csv')

In [4]:
dataset

   Sex  Weight(Sep)  Weight(Apr)  BMI(Sep)  BMI(Apr)
0    M         72.0         59.0     22.02     18.14
1    M         97.0         86.0     19.70     19.14
2    M         74.0         69.0     24.09     22.43
3    M          NaN         88.0     26.97     25.57
4    F         68.0         64.0     21.51     20.10
5    M         59.0         55.0     18.69     17.40
6    F         64.0          NaN     24.24     22.88
7    F         56.0         53.0     21.23     20.23
8    F         70.0         68.0     30.26     29.24
9    F         58.0         56.0     21.88     21.02
10   F         50.0         47.0     21.57     16.89
11   M         71.0         69.0     24.57     23.85
12   M          NaN         66.0     20.68     20.15
13   F         56.0         55.0     20.97     20.36
14   F         70.0         68.0     27.30     26.73
15   F         61.0         60.0     23.30     22.88
16   F         53.0         52.0     19.48     19.24
17   M         92.0         92.0     24.74     24.69
18   F         57.0         58.0     20.69     20.79
19   M         67.0         67.0     20.49     20.60
20   F         58.0         58.0     21.09     21.24
21   F         49.0         50.0     18.37     18.53
22   M         68.0         68.0     22.40     22.61
23   F         69.0          NaN     28.17     28.43
24   M         87.0         88.0     23.60     23.81
25   M         81.0         82.0     26.52     26.78
26   M         60.0         61.0     18.89     19.27
27   F         52.0         53.0     19.31     19.75
28   M         70.0         71.0     20.96     21.32
29   F         63.0         64.0     21.78     22.22
30   F         56.0         57.0     19.78     22.32
31   M         68.0         69.0     22.40     22.82
32   M         68.0         69.0     22.76     23.19
33   F         54.0         56.0     20.15     20.69
34   M         80.0         82.0     22.14     22.57
35   M         64.0         66.0     20.27     20.76
36   F         57.0         59.0     22.15     22.93
37   F         63.0         65.0     23.87     24.67
38   F         54.0         56.0     18.61     19.34
39   F         56.0         58.0     21.73     22.58

In [6]:
X = dataset.iloc[:, :-2].values
Y = dataset.iloc[:, -2].values

In [8]:
print(X)

[['M' 72.0 59.0]
 ['M' 97.0 86.0]
 ['M' 74.0 69.0]
 ['M' nan 88.0]
 ['F' 68.0 64.0]
 ['M' 59.0 55.0]
 ['F' 64.0 nan]
 ['F' 56.0 53.0]
 ['F' 70.0 68.0]
 ['F' 58.0 56.0]
 ['F' 50.0 47.0]
 ['M' 71.0 69.0]
 ['M' nan 66.0]
 ['F' 56.0 55.0]
 ['F' 70.0 68.0]
 ['F' 61.0 60.0]
 ['F' 53.0 52.0]
 ['M' 92.0 92.0]
 ['F' 57.0 58.0]
 ['M' 67.0 67.0]
 ['F' 58.0 58.0]
 ['F' 49.0 50.0]
 ['M' 68.0 68.0]
 ['F' 69.0 nan]
 ['M' 87.0 88.0]
 ['M' 81.0 82.0]
 ['M' 60.0 61.0]
 ['F' 52.0 53.0]
 ['M' 70.0 71.0]
 ['F' 63.0 64.0]
 ['F' 56.0 57.0]
 ['M' 68.0 69.0]
 ['M' 68.0 69.0]
 ['F' 54.0 56.0]
 ['M' 80.0 82.0]
 ['M' 64.0 66.0]
 ['F' 57.0 59.0]
 ['F' 63.0 65.0]
 ['F' 54.0 56.0]
 ['F' 56.0 58.0]]

In [9]:
print(Y)

[22.02 19.7  24.09 26.97 21.51 18.69 24.24 21.23 30.26 21.88 21.57 24.57
 20.68 20.97 27.3  23.3  19.48 24.74 20.69 20.49 21.09 18.37 22.4  28.17
 23.6  26.52 18.89 19.31 20.96 21.78 19.78 22.4  22.76 20.15 22.14 20.27
 22.15 23.87 18.61 21.73]

# Handling the missing data

In [10]:
#We should eliminate missing values by eliminating those rows but it is not effective when there are many missing rows
#Another method is to fill them with mean or median
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [11]:
print(X)

[['M' 72.0 59.0]
 ['M' 97.0 86.0]
 ['M' 74.0 69.0]
 ['M' 65.05263157894737 88.0]
 ['F' 68.0 64.0]
 ['M' 59.0 55.0]
 ['F' 64.0 64.84210526315789]
 ['F' 56.0 53.0]
 ['F' 70.0 68.0]
 ['F' 58.0 56.0]
 ['F' 50.0 47.0]
 ['M' 71.0 69.0]
 ['M' 65.05263157894737 66.0]
 ['F' 56.0 55.0]
 ['F' 70.0 68.0]
 ['F' 61.0 60.0]
 ['F' 53.0 52.0]
 ['M' 92.0 92.0]
 ['F' 57.0 58.0]
 ['M' 67.0 67.0]
 ['F' 58.0 58.0]
 ['F' 49.0 50.0]
 ['M' 68.0 68.0]
 ['F' 69.0 64.84210526315789]
 ['M' 87.0 88.0]
 ['M' 81.0 82.0]
 ['M' 60.0 61.0]
 ['F' 52.0 53.0]
 ['M' 70.0 71.0]
 ['F' 63.0 64.0]
 ['F' 56.0 57.0]
 ['M' 68.0 69.0]
 ['M' 68.0 69.0]
 ['F' 54.0 56.0]
 ['M' 80.0 82.0]
 ['M' 64.0 66.0]
 ['F' 57.0 59.0]
 ['F' 63.0 65.0]
 ['F' 54.0 56.0]
 ['F' 56.0 58.0]]

#  ENCODING CATEGORICAL DATA

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])

In [13]:
X

array([[1, 72.0, 59.0],
       [1, 97.0, 86.0],
       [1, 74.0, 69.0],
       [1, 65.05263157894737, 88.0],
       [0, 68.0, 64.0],
       [1, 59.0, 55.0],
       [0, 64.0, 64.84210526315789],
       [0, 56.0, 53.0],
       [0, 70.0, 68.0],
       [0, 58.0, 56.0],
       [0, 50.0, 47.0],
       [1, 71.0, 69.0],
       [1, 65.05263157894737, 66.0],
       [0, 56.0, 55.0],
       [0, 70.0, 68.0],
       [0, 61.0, 60.0],
       [0, 53.0, 52.0],
       [1, 92.0, 92.0],
       [0, 57.0, 58.0],
       [1, 67.0, 67.0],
       [0, 58.0, 58.0],
       [0, 49.0, 50.0],
       [1, 68.0, 68.0],
       [0, 69.0, 64.84210526315789],
       [1, 87.0, 88.0],
       [1, 81.0, 82.0],
       [1, 60.0, 61.0],
       [0, 52.0, 53.0],
       [1, 70.0, 71.0],
       [0, 63.0, 64.0],
       [0, 56.0, 57.0],
       [1, 68.0, 69.0],
       [1, 68.0, 69.0],
       [0, 54.0, 56.0],
       [1, 80.0, 82.0],
       [1, 64.0, 66.0],
       [0, 57.0, 59.0],
       [0, 63.0, 65.0],
       [0, 54.0, 56.0],
       [0, 56.0, 58.0]], dtype=object)

In [15]:
# OneHotEncoding using columntransfer
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],
    remainder='passthrough'
)

X = ct.fit_transform(X)

In [16]:
print(X)

[[1.0 0.0 1.0 72.0 59.0]
 [1.0 0.0 1.0 97.0 86.0]
 [1.0 0.0 1.0 74.0 69.0]
 [1.0 0.0 1.0 65.05263157894737 88.0]
 [0.0 1.0 0.0 68.0 64.0]
 [1.0 0.0 1.0 59.0 55.0]
 [0.0 1.0 0.0 64.0 64.84210526315789]
 [0.0 1.0 0.0 56.0 53.0]
 [0.0 1.0 0.0 70.0 68.0]
 [0.0 1.0 0.0 58.0 56.0]
 [0.0 1.0 0.0 50.0 47.0]
 [1.0 0.0 1.0 71.0 69.0]
 [1.0 0.0 1.0 65.05263157894737 66.0]
 [0.0 1.0 0.0 56.0 55.0]
 [0.0 1.0 0.0 70.0 68.0]
 [0.0 1.0 0.0 61.0 60.0]
 [0.0 1.0 0.0 53.0 52.0]
 [1.0 0.0 1.0 92.0 92.0]
 [0.0 1.0 0.0 57.0 58.0]
 [1.0 0.0 1.0 67.0 67.0]
 [0.0 1.0 0.0 58.0 58.0]
 [0.0 1.0 0.0 49.0 50.0]
 [1.0 0.0 1.0 68.0 68.0]
 [0.0 1.0 0.0 69.0 64.84210526315789]
 [1.0 0.0 1.0 87.0 88.0]
 [1.0 0.0 1.0 81.0 82.0]
 [1.0 0.0 1.0 60.0 61.0]
 [0.0 1.0 0.0 52.0 53.0]
 [1.0 0.0 1.0 70.0 71.0]
 [0.0 1.0 0.0 63.0 64.0]
 [0.0 1.0 0.0 56.0 57.0]
 [1.0 0.0 1.0 68.0 69.0]
 [1.0 0.0 1.0 68.0 69.0]
 [0.0 1.0 0.0 54.0 56.0]
 [1.0 0.0 1.0 80.0 82.0]
 [1.0 0.0 1.0 64.0 66.0]
 [0.0 1.0 0.0 57.0 59.0]
 [0.0 1.0 0.0 63.0 65.0]
 [0.0 1.0 0.0 54.0 56.0]
 [0.0 1.0 0.0 56.0 58.0]]

# SPLITTING THE DATASET

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=0)

# FEATURE SCALING

In [18]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

In [19]:
X_train

array([[-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -6.96461537e-01, -6.13997323e-01],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -1.63933412e-01, -7.49209729e-02],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -1.14023498e+00, -1.06322761e+00],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
        -7.51787239e-02,  1.04771144e-01],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -1.63933412e-01,  1.49250853e-02],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
         8.12368153e-01,  3.74309318e-01],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -7.85216225e-01, -6.13997323e-01],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -7.85216225e-01, -7.03843381e-01],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
         1.34489628e+00,  1.54230808e+00],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -1.05148029e+00, -1.15307367e+00],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -6.96461537e-01, -5.24151264e-01],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
         4.57349402e-01,  2.84463260e-01],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -7.85216225e-01, -8.83535498e-01],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
        -5.18952162e-01, -8.83535498e-01],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
         2.40995253e+00,  2.44076866e+00],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
         4.57349402e-01,  2.84463260e-01],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -9.62725600e-01, -7.93689439e-01],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -7.85216225e-01, -1.06322761e+00],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
         2.79840027e-01,  3.74309318e-01],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
         2.85372597e+00,  1.90169231e+00],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
        -4.30197474e-01, -3.44459148e-01],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
         1.82472631e-02,  1.04771144e-01],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
         2.79840027e-01,  3.74309318e-01],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
         1.96617909e+00,  2.08138443e+00],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -7.51787239e-02,  7.38865611e-04],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
         3.68594714e-01,  7.38865611e-04],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -1.40649904e+00, -1.33276579e+00],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
         1.91085339e-01,  1.94617202e-01],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -6.07706850e-01, -7.93689439e-01],
       [-8.81917104e-01,  8.81917104e-01, -8.81917104e-01,
        -9.62725600e-01, -7.93689439e-01],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
         1.82472631e-02,  2.08138443e+00],
       [ 1.13389342e+00, -1.13389342e+00,  1.13389342e+00,
         6.34858777e-01, -5.24151264e-01]])

In [21]:
X_test

array([[ 1.        , -1.        ,  1.        ,  0.24160308,  0.32299095],
       [-1.        ,  1.        , -1.        , -0.89535257, -0.71058008],
       [ 1.        , -1.        ,  1.        ,  1.71964542,  1.76999039],
       [-1.        ,  1.        , -1.        ,  0.24160308, -0.09043746],
       [-1.        ,  1.        , -1.        , -1.80491709, -1.84750821],
       [-1.        ,  1.        , -1.        , -0.55426588, -0.50386588],
       [ 1.        , -1.        ,  1.        ,  0.46899421,  0.63306225],
       [ 1.        , -1.        ,  1.        ,  0.58268977,  0.42634805]])